events {
    worker_connections 1024;
}

http {
    upstream login_service {
        server login-service:3000;
    }
    upstream matchmaking_service {
        server matchmaking-service:3000;
    }
    upstream user_service {
        server user-service:3000;
    }
    upstream chat_service {
        server chat-service:3000;
    }
    upstream ranking_service {
        server ranking-service:3000;
    }

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=1r/s;

    server {
        listen 80;
        server_name_;

        location /api/auth/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://login_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/match/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://matchmaking_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/users/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/chat/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://chat_service;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ranking/ {
            limit_req zone=api_limit burst=20 nodelay;
            proxy_pass http://ranking_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /health {
            access_log off;
            return 200 "ok\n";
        }

    }

}